--
-- load the GSE607 data into bartonlab
--

--
-- the experiment schema
--
DROP SCHEMA gse607 CASCADE;
CREATE SCHEMA gse607;

-------------------+-------------------+------------------------
-- experiments (insert row in public table)
-------------------+-------------------+------------------------
-- schema          | character varying | not null
-- title           | character varying | not null
-- description     | character varying | 
-- notes           | character varying | 
-- geoseries       | character varying | 
-- geodataset      | character varying | 
-- pmid            | integer           | 
-- expressionlabel | character varying | 
-- contributors    | character varying | 
-- publicdata      | boolean           | not null default false
-- assay           | character varying | 
-- annotation      | character varying | 
-- genus           | character varying | 
-- species         | character varying |

DELETE FROM experiments WHERE schema='gse607';
INSERT INTO experiments VALUES (
       'gse607',
       'Arabidopsis thaliana leaf, stem and flower tissues.',
       'Analysis of gene expression in Arabidopsis thaliana leaf, stem and flower tissues.',
       'Columbia (Col-0) Arabidopsis thaliana plants were grown at a density of 4 plants per 5 inch square pot either in a growth chamber or a green house set to 25*C by day, 20*C by night. Days were set to a 16hr photoperiod with 125 micro mol m-2s-1 fluorescent irradiation. Expanding leaves were harvested 15 days post germination in the middle of the photoperiod (3 replicates). Expanding upper 2" of the stem with siliques and pedicels removed were harvested 29 days post germination in the middle of the photoperiod (4 replicates). Developed flowers and unopened buds were harvested 29 days post germination in the middle of the photoperiod (4 replicates). RNA and Microarray Methods: Total RNA was extracted from the plants using the Trizol method (Invitrogen, Ramonell et al. (2002) Mol. Plant Pathol. 3: 301) and purified with a silica membrane column (Qiagen, RNeasy). Twenty micrograms biotinylated complementary RNA (cRNA) was prepared as described (Hernan et al. (2003) Cancer Res. 63, 140) from the purified total RNA. The resulting cRNA was used to hybridize ATH1 Arabidopsis GeneChips (Affymetrix) using the manufacturer''s protocols. The array images were analyzed with the Affymetrix Microarray Suite 5.0 software with the target intensity set to 500. Normalized signal intensities were generated by multiplying signal intensities by ratio figure which set GapC (ID_REF = 258588_s_at) to 8500.',
       'GSE607',
       NULL,
       15178800,
       'GEO series matrix expression',
       'Bergmann DC, Lukowitz W, Somerville CR',
       true,
       'Microarray',
       'TAIR10',
       'Arabidopsis',
       'thaliana'
);

-----------------+-------------------+------------------------
-- gse607.samples
-----------------+-------------------+------------------------
-- label         | character varying | not null
-- num           | integer           | not null
-- condition     | character varying | not null
-- control       | boolean           | not null default false
-- time          | integer           | 
-- comment       | character varying | 
-- replicate     | integer           | 
-- internalscale | double precision  | not null default 1.0

CREATE TABLE gse607.samples () INHERITS (public.samples);
COPY gse607.samples FROM '/home/shokin/BartonLab/GSE607/samples.tsv' WITH CSV HEADER DELIMITER AS '	';

-------------------------------------------------------
-- gse607.expression - use ordering of samples above!
-------------------------------------------------------

CREATE TABLE gse607.expression () INHERITS (public.expression);

-- load the seriesmatrix data from a single text file
CREATE TEMP TABLE seriesmatrix (
       probe_set_id   varchar,
       gsm9223        double precision,
       gsm9224        double precision,
       gsm9225        double precision,
       gsm9226        double precision,
       gsm9227        double precision,
       gsm9228        double precision,
       gsm9229        double precision,
       gsm9230        double precision,
       gsm9231        double precision,
       gsm9232        double precision,
       gsm9233        double precision
       );
COPY seriesmatrix FROM '/home/shokin/BartonLab/GSE607/seriesmatrix.tsv' WITH CSV HEADER DELIMITER AS '	';

-- drop not null so we can insert the probeset ids into expression table first
ALTER TABLE gse607.expression ALTER COLUMN values DROP NOT NULL;

-- create the rows by inserting the probeset ids
INSERT INTO gse607.expression (probe_set_id) SELECT probe_set_id FROM seriesmatrix;

-- update the table data column by data column using array(), being sure to order by num to get the array values in the correct order
UPDATE gse607.expression SET values = (
       SELECT array[
       gsm9223,
       gsm9224,
       gsm9225,
       gsm9226,
       gsm9227,
       gsm9228,
       gsm9229,
       gsm9230,
       gsm9231,
       gsm9232,
       gsm9233
       ]
       FROM seriesmatrix WHERE seriesmatrix.probe_set_id=expression.probe_set_id
       );

-- restore not null
ALTER TABLE gse607.expression ALTER COLUMN values SET NOT NULL;

-- import the gene ids
UPDATE gse607.expression SET id = (SELECT transcript_id FROM affxannot WHERE affxannot.probe_set_id=gse607.expression.probe_set_id);


-- reassign ownership
REASSIGN OWNED BY sam TO bartonlab;
REASSIGN OWNED BY shokin TO bartonlab;
